### PR TITLE
Remove mlb and retro mports. Start Replacing with generic mport.

### PR DESCRIPTION
**Pull request by ghost**
# BREAKING REPOSITORY PULL REQUEST

## Current repository would be BROKEN DURING REBUILD

> Removing mlb and retro is a concept rebuild
> > First step in rebuild requires Removal of mlb and retro

> Rebuild is currently unusable
> > **Accepting pull request prior to rebuild completion will BREAK REPOSITORY**

### CODE REVIEW

**Comment by eeshvardasikcm** [comment]
These deletions may work as a branch that has no import feature or has room for new import sources.

**Comment by ghost** [comment]
These changes reflect what I would do here.

You don't have to accept my pull request.

I wouldn't be offended.

> Currently I am working on creating or finding a dynamic (random bounded) XML data storage system to port my project management into java at the moment. Possible solution is to make generic schema for port. A left handed hitter is a left handed hitter no matter what league. I'm doing a baseball systems modeling repository anyway.

**Comment by cretz** [comment]
To be honest, I haven't even looked at this repo in a decade, heh. I'm not sure I'd be up for merging anything here, but feel free to take any of the code to your own project. I don't even know what works and what doesn't (or even how far I got when I originally wrote this stuff).

**Comment by ghost** [comment]
> To be honest, I haven't even looked at this repo in a decade, heh. I'm not sure I'd be up for merging anything here, but feel free to take any of the code to your own project. I don't even know what works and what doesn't (or even how far I got when I originally wrote this stuff).

It's good code. Thanks. Communication is good. Thanks. Have fun at the Ballpark.

**Pull request closed without merging**
